# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61e832b5ec9acbd3dd5f135309935c54f96a84f43976c170b1d2206f2432d089b263b58a34bed43a0f686a7bd867a5ee3e5ad7d58dd86079bdcc9111cc8ee58

test:
  secret_key_base: 0e84e90721c6965728f1ca6cea907a03735eab214aee516c4b1ee8c64b88cd43cb0a7a25f23ac22745ef6e59ebaf43f9082fcd85716d39cd9313ff69178db37d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
